### ISSUE TITLE
[Help] I am unable to run it successfully.

### ISSUE THREAD

**Issue by xmenw** [jbilcke-hf/ai-comic-factory#10]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (ai-comic-factory/node_modules/.pnpm/next@13.4.10_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/undici/index.js:1:82152)
      at ai-comic-factory/node_modules/.pnpm/next@13.4.10_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/undici/index.js:1:81644
      at Immediate._onImmediate (ai-comic-factory/node_modules/.pnpm/next@13.4.10_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/undici/index.js:1:82034)
      at process.processImmediate (node:internal/timers:476:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

I am using the INFERENCE_API method, and I have configured everything in the .env file, but every time I enter the prompt and click "Go," it gives an error. Am I using the method incorrectly? To be straightforward, I've installed all the packages and performed the standard operations. Do I still need to start Docker?

**Comment by jbilcke-hf** [comment]
Hi,

do you wish to use the default SDXL model or a custom one?

If it's a custom one, you can try first using the cloud-hosted version, to check it it works properly:
<img width="902" alt="Capture d’écran 2023-11-20 à 15 49 59" src="https://github.com/jbilcke-hf/ai-comic-factory/assets/137051437/3bfcb1cd-0a21-4bcc-abf2-452e5fc01882">

If everything works fine in the cloud app, then you can attempt to run it on your fork of the repository

usually the issue might come from a hugging face token not properly configured in the `.env.local` file

you can also try to use another engine (eg. replicate) to see if it changes something
